### ISSUE TITLE
Getting errors on first run (Example doesn't run without fixes)

### ISSUE THREAD

**Issue by frostyandy2k** [weaveworks/grafanalib#196]
##  What did you expect to happen?
Copy paste example and run to generate the dashboard json.

## What happened?

Errors:
- #180  (Not documented and version 0.5.4 not available on pip yet)
- After downgrading to 'attrs==19.1.0' --force-reinstall `NameError: name 'G' is not defined
`
- output JSON was flawed, missed a `dashboard` parent element

## How to reproduce it?

grafanalib v0.5.3

```
docker run -it python:3.6-alpine3.10 sh
or 
docker run -it python:2-alpine sh 
apk update && apk add vim
pip install 'attrs==19.1.0' --force-reinstall
pip install grafanalib
vim frontend.dashboard.py #paste example from README
generate-dashboard -o frontend.json frontend.dashboard.py
```

**Comment by frostyandy2k** [comment]
frontend.dashboard.py:

`from grafanalib.core import *`

needs to be 

```
import grafanalib.core as G  # General Grafana objects
from grafanalib.core import *
```

The output needs to be wrapped in `{ dashboard{ ... } }`

```
{"dashboard": {

  "__inputs": [], 
  "annotations": {
    "list": []
  }, 
  "editable": true, 
  "gnetId": null, 
  "hideControls": false, 
  "id": null, 
  "links": [], 
  "refresh": "10s", 
  "rows": [
    {
      "collapse": false, 
      "editable": true, 
      "height": "250px", 
      "panels": [
        {
          "alert": {
            "conditions": [
              {
                "evaluator": {
                  "params": [
                    5
                  ], 
                  "type": "gt"
                }, 
                "operator": {
                  "type": "and"
                }, 
                "query": {
                  "model": {
                    "datasource": "", 
                    "expr": "sum(irate(nginx_http_requests_total{job=\"default/frontend\",status=~\"5..\"}[1m]))", 
                    "format": "time_series", 
                    "instant": false, 
                    "interval": "", 
                    "intervalFactor": 2, 
                    "legendFormat": "5xx", 
                    "metric": "", 
                    "refId": "A", 
                    "step": 10, 
                    "target": ""
                  }, 
                  "params": [
                    "A", 
                    "5m", 
                    "now"
                  ]
                }, 
                "reducer": {
                  "params": [], 
                  "type": "sum"
                }, 
                "type": "query"
              }
            ], 
            "executionErrorState": "alerting", 
            "frequency": "60s", 
            "handler": 1, 
            "message": "More than 5 QPS of 500s on Nginx for 5 minutes", 
            "name": "Too many 500s on Nginx", 
            "noDataState": "no_data", 
            "notifications": []
          }, 
          "aliasColors": {}, 
          "bars": false, 
          "datasource": "X", 
          "description": null, 
          "editable": true, 
          "error": false, 
          "fill": 1, 
          "grid": {
            "threshold1": null, 
            "threshold1Color": "rgba(216, 200, 27, 0.27)", 
            "threshold2": null, 
            "threshold2Color": "rgba(234, 112, 112, 0.22)"
          }, 
          "id": 1, 
          "isNew": true, 
          "legend": {
            "alignAsTable": false, 
            "avg": false, 
            "current": false, 
            "hideEmpty": false, 
            "hideZero": false, 
            "max": false, 
            "min": false, 
            "rightSide": false, 
            "show": true, 
            "sideWidth": null, 
            "sort": null, 
            "sortDesc": false, 
            "total": false, 
            "values": false
          }, 
          "lines": true, 
          "linewidth": 2, 
          "links": [], 
          "minSpan": null, 
          "nullPointMode": "connected", 
          "percentage": false, 
          "pointradius": 5, 
          "points": false, 
          "renderer": "flot", 
          "repeat": null, 
          "seriesOverrides": [], 
          "span": 6.0, 
          "stack": false, 
          "steppedLine": false, 
          "targets": [
            {
              "datasource": "", 
              "expr": "sum(irate(nginx_http_requests_total{job=\"default/frontend\",status=~\"1..\"}[1m]))", 
              "format": "time_series", 
              "instant": false, 
              "interval": "", 
              "intervalFactor": 2, 
              "legendFormat": "1xx", 
              "metric": "", 
              "refId": "A", 
              "step": 10, 
              "target": ""
            }, 
            {
              "datasource": "", 
              "expr": "sum(irate(nginx_http_requests_total{job=\"default/frontend\",status=~\"2..\"}[1m]))", 
              "format": "time_series", 
              "instant": false, 
              "interval": "", 
              "intervalFactor": 2, 
              "legendFormat": "2xx", 
              "metric": "", 
              "refId": "B", 
              "step": 10, 
              "target": ""
            }, 
            {
              "datasource": "", 
              "expr": "sum(irate(nginx_http_requests_total{job=\"default/frontend\",status=~\"3..\"}[1m]))", 
              "format": "time_series", 
              "instant": false, 
              "interval": "", 
              "intervalFactor": 2, 
              "legendFormat": "3xx", 
              "metric": "", 
              "refId": "C", 
              "step": 10, 
              "target": ""
            }, 
            {
              "datasource": "", 
              "expr": "sum(irate(nginx_http_requests_total{job=\"default/frontend\",status=~\"4..\"}[1m]))", 
              "format": "time_series", 
              "instant": false, 
              "interval": "", 
              "intervalFactor": 2, 
              "legendFormat": "4xx", 
              "metric": "", 
              "refId": "D", 
              "step": 10, 
              "target": ""
            }, 
            {
              "datasource": "", 
              "expr": "sum(irate(nginx_http_requests_total{job=\"default/frontend\",status=~\"5..\"}[1m]))", 
              "format": "time_series", 
              "instant": false, 
              "interval": "", 
              "intervalFactor": 2, 
              "legendFormat": "5xx", 
              "metric": "", 
              "refId": "E", 
              "step": 10, 
              "target": ""
            }
          ], 
          "timeFrom": null, 
          "timeShift": null, 
          "title": "Frontend QPS", 
          "tooltip": {
            "msResolution": true, 
            "shared": true, 
            "sort": 0, 
            "value_type": "cumulative"
          }, 
          "transparent": false, 
          "type": "graph", 
          "xaxis": {
            "show": true
          }, 
          "yaxes": [
            {
              "decimals": null, 
              "format": "ops", 
              "label": null, 
              "logBase": 1, 
              "max": null, 
              "min": 0, 
              "show": true
            }, 
            {
              "decimals": null, 
              "format": "short", 
              "label": null, 
              "logBase": 1, 
              "max": null, 
              "min": 0, 
              "show": true
            }
          ]
        }, 
        {
          "aliasColors": {}, 
          "bars": false, 
          "datasource": "My Prometheus", 
          "description": null, 
          "editable": true, 
          "error": false, 
          "fill": 1, 
          "grid": {
            "threshold1": null, 
            "threshold1Color": "rgba(216, 200, 27, 0.27)", 
            "threshold2": null, 
            "threshold2Color": "rgba(234, 112, 112, 0.22)"
          }, 
          "id": 2, 
          "isNew": true, 
          "legend": {
            "alignAsTable": false, 
            "avg": false, 
            "current": false, 
            "hideEmpty": false, 
            "hideZero": false, 
            "max": false, 
            "min": false, 
            "rightSide": false, 
            "show": true, 
            "sideWidth": null, 
            "sort": null, 
            "sortDesc": false, 
            "total": false, 
            "values": false
          }, 
          "lines": true, 
          "linewidth": 2, 
          "links": [], 
          "minSpan": null, 
          "nullPointMode": "connected", 
          "percentage": false, 
          "pointradius": 5, 
          "points": false, 
          "renderer": "flot", 
          "repeat": null, 
          "seriesOverrides": [], 
          "span": 6.0, 
          "stack": false, 
          "steppedLine": false, 
          "targets": [
            {
              "datasource": "", 
              "expr": "histogram_quantile(0.5, sum(irate(nginx_http_request_duration_seconds_bucket{job=\"default/frontend\"}[1m])) by (le))", 
              "format": "time_series", 
              "instant": false, 
              "interval": "", 
              "intervalFactor": 2, 
              "legendFormat": "0.5 quantile", 
              "metric": "", 
              "refId": "A", 
              "step": 10, 
              "target": ""
            }, 
            {
              "datasource": "", 
              "expr": "histogram_quantile(0.99, sum(irate(nginx_http_request_duration_seconds_bucket{job=\"default/frontend\"}[1m])) by (le))", 
              "format": "time_series", 
              "instant": false, 
              "interval": "", 
              "intervalFactor": 2, 
              "legendFormat": "0.99 quantile", 
              "metric": "", 
              "refId": "B", 
              "step": 10, 
              "target": ""
            }
          ], 
          "timeFrom": null, 
          "timeShift": null, 
          "title": "Frontend latency", 
          "tooltip": {
            "msResolution": true, 
            "shared": true, 
            "sort": 0, 
            "value_type": "cumulative"
          }, 
          "transparent": false, 
          "type": "graph", 
          "xaxis": {
            "show": true
          }, 
          "yaxes": [
            {
              "decimals": null, 
              "format": "s", 
              "label": null, 
              "logBase": 1, 
              "max": null, 
              "min": 0, 
              "show": true
            }, 
            {
              "decimals": null, 
              "format": "short", 
              "label": null, 
              "logBase": 1, 
              "max": null, 
              "min": 0, 
              "show": true
            }
          ]
        }
      ], 
      "repeat": null, 
      "showTitle": false, 
      "title": "New row"
    }
  ], 
  "schemaVersion": 12, 
  "sharedCrosshair": false, 
  "style": "dark", 
  "tags": [], 
  "templating": {
    "list": []
  }, 
  "time": {
    "from": "now-1h", 
    "to": "now"
  }, 
  "timepicker": {
    "refresh_intervals": [
      "5s", 
      "10s", 
      "30s", 
      "1m", 
      "5m", 
      "15m", 
      "30m", 
      "1h", 
      "2h", 
      "1d"
    ], 
    "time_options": [
      "5m", 
      "15m", 
      "1h", 
      "6h", 
      "12h", 
      "24h", 
      "2d", 
      "7d", 
      "30d"
    ]
  }, 
  "timezone": "utc", 
  "title": "Frontend Stats", 
  "uid": null, 
  "version": 0
}
}
```

**Comment by maria-valero** [comment]
Including that line solves the problem

**Comment by dholbach** [comment]
This is fixed in 0.5.5.

**Comment by xkbarkar** [comment]
* output JSON was flawed, missed a dashboard parent element 
This is still missing using the example in 5.5
