### ISSUE TITLE
AverageMetricAgg in elasticsearch panels is broken and does not instantiate properly

### ISSUE THREAD

**Issue by ljades** [weaveworks/grafanalib#245]
## What you expected to happen?

Instantiating an AverageMetricAgg should include an id field with a default.

## What happened?

id is not defined as a field, and then to_json_data() tries to set id to `self.id`, which leads nowhere.

```
[...] line 78, in to_json_data
    'id': str(self.id),
AttributeError: 'AverageMetricAgg' object has no attribute 'id'
```

## How to reproduce it?
Try instantiating an AverageMetricAgg

**Comment by dholbach** [comment]
This is fixed in `master`, will be part of the next release.

**Comment by ljades** [comment]
I'm still seeing the issue in the code on master https://github.com/weaveworks/grafanalib/blob/master/grafanalib/elasticsearch.py#L74

**Comment by dholbach** [comment]
@ljades Is this fixed for you now? We'll release 0.5.7 later on. I seemed to have gotten a notification from you saying that it was still a problem?

**Comment by ljades** [comment]
Yes, sorry. It is showing up for me now, but it wasn't before. It might have been a caching issue on my local end, and when I refreshed the fixed version appeared, which is why I deleted the message.

**Comment by dholbach** [comment]
Super - thanks for following up!
